### ISSUE TITLE
node indicates it is not synced while it is

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#14] opened 2018-03-05 10:06 UTC
```
rob$ ./tfchainc
Synced: No
Height: 656
Progress (estimated): 0%
```
<img width="626" alt="screen shot 2018-03-05 at 11 05 03" src="https://user-images.githubusercontent.com/3511318/36969210-2a59a116-2065-11e8-8856-a0ca5b9ba00d.png">

**Comment by robvanmieghem** [comment] 2018-03-05 10:21
solved itself: 
```
./tfchainc
Synced: Yes
Block:  6990c99369eab71321137d0353284e87189fd45f8384249a28143094b735ef29
Height: 658
Target: [0 0 0 17 229 76 103 40 116 218 229 5 25 140 9 213 179 108 241 11 184 11 188 61 122 37 167 161 10 238 184 30]
```

**Comment by robvanmieghem** [comment] 2018-04-03 13:42
reopened since it takes hours, probably because not enough peers available

**Comment by GlenDC** [comment] 2018-04-03 13:43
It is exactly because of that. Therefore we closed it last time. Unless you think this is unexpected behavior?

**Comment by GlenDC** [comment] 2018-04-09 12:27
Even if there are 50+ peers connected, it still takes a while before this property becomes true. Perhaps this is desired, perhaps not, anyhow it is in a confusion representation as it is.

Need to continue looking into this next milestone.

**Comment by robvanmieghem** [comment] 2018-04-17 10:43
lowering the number of required synced outbound peers to 3

**Closed** 2018-04-29 12:12 UTC
Labels: state_inprogress
