### ISSUE TITLE
panic: runtime error:  On running "tfchainc atomicswap auditcontract" with optional --amount flag

### ISSUE THREAD

**Issue by konceptzer0** [threefoldfoundation/tfchain#127] opened 2018-06-07 17:01 UTC
v1.0.6

```
root@51b533844e7b:/bin# tfchainc atomicswap auditcontract d7ab82eeba163846d2edf28c4ecfcc9933d1bf2fb49b3b11bba314170bf85615 --amount 2
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x517af0]

goroutine 1 [running]:
math/big.(*Int).Mul(0xc420116e20, 0xc420116e20, 0x0, 0xa)
	/usr/lib/go-1.10/src/math/big/int.go:161 +0xe0
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/client.CurrencyConvertor.ParseCoinString(0x0, 0x0, 0x7ffff01e3968, 0x1, 0x2, 0xc4201ba3c0, 0x8ae3ed, 0xc42018e9c0, 0x8ae3ed, 0x6)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/client/parse.go:73 +0x6e1
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/client.(*coinFlag).Set(0xbf1868, 0x7ffff01e3968, 0x1, 0x6, 0xc42018ea58)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/client/flag.go:23 +0x51
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag.(*FlagSet).Set(0xc4201ba3c0, 0x8ae3ed, 0x6, 0x7ffff01e3968, 0x1, 0xc42018e9e8, 0x6)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag/flag.go:432 +0xe2
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag.(*FlagSet).Parse.func1(0xc4200b1cc0, 0x7ffff01e3968, 0x1, 0x6, 0xc42018ea58)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag/flag.go:1028 +0x54
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag.(*FlagSet).parseLongArg(0xc4201ba3c0, 0x7ffff01e395f, 0x8, 0xc42020e350, 0x1, 0x1, 0xc420065fa0, 0xc4201ba3c0, 0x7f4ca459b000, 0x0, ...)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag/flag.go:914 +0x290
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag.(*FlagSet).parseArgs(0xc4201ba3c0, 0xc42020e350, 0x1, 0x1, 0xc420065fa0, 0x3, 0xc4201ba3c0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag/flag.go:1003 +0x4ca
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag.(*FlagSet).Parse(0xc4201ba3c0, 0xc42020e330, 0x3, 0x3, 0x8acfea, 0x4)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/pflag/flag.go:1031 +0xfa
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).ParseFlags(0xbd3980, 0xc42020e330, 0x3, 0x3, 0xc42013da70, 0x74e36d)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:1368 +0xb2
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).execute(0xbd3980, 0xc42020e330, 0x3, 0x3, 0xbd3980, 0xc42020e330)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:645 +0x91
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200b8d80, 0x1, 0xc4200962a0, 0x51)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200b8d80, 0xbf1300, 0x8ace6a)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/client.DefaultCLIClient(0x0, 0x0, 0x8b007c, 0x7, 0xc4200ac6e0)
	/root/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/client/defaultclient.go:280 +0xe42
main.main()
	/root/go/src/github.com/threefoldfoundation/tfchain/cmd/tfchainc/main.go:10 +0x193

```

**Comment by GlenDC** [comment] 2018-06-07 21:37
This is a new bug since today, as it is caused by code I pushed earlier today.

However as to not get blocked until I resolve this,
you could checkout commit 679d6818f236f150e24041c143a287252981ba5a. That's the commit prior to the commit where the bug you report here got introduced. Or if you want a stable release you can also checkout the `v1.0.6` tag. Both work. Choose something, check it out and build using `make install-std`. Should unblock you for now, until I fix this bug.

**Comment by GlenDC** [comment] 2018-06-08 14:04
This is now resolved in master @konceptzer0, should you desire it you can get latest now.

**Closed** 2018-06-08 14:05 UTC
Labels: priority_critical, state_inprogress, type_bug
